### ISSUE TITLE
Enhancement : Overflow-x

### ISSUE THREAD

**Issue by TartejBrothers** [polpielladev/polpiella.dev#30]
The site is perfect, but doesn't have overflow x set.
Try using 
```css
body{
      overflow-x: hidden; 
}
```
It should solve the problem with the thing moving left and right while scrolling horizontally.
